# Generated by Django 5.2 on 2026-04-17 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='z.B. "Nr. 1" oder "Schlüssel A"', max_length=50, verbose_name='Schlüsselnummer / Bezeichnung')),
                ('notes', models.TextField(blank=True, verbose_name='Bemerkungen')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Schlüssel',
                'verbose_name_plural': 'Schlüssel',
                'ordering': ['key_type__order', 'key_type__name', 'number'],
            },
        ),
        migrations.CreateModel(
            name='KeyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Bezeichnung')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('color', models.CharField(default='#c0000c', help_text='Farbe zur visuellen Unterscheidung, z.B. #c0000c', max_length=7, verbose_name='Farbe (Hex)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Reihenfolge')),
            ],
            options={
                'verbose_name': 'Schlüsseltyp',
                'verbose_name_plural': 'Schlüsseltypen',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='KeyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder_name', models.CharField(max_length=200, verbose_name='Name des Schlüsselinhabers')),
                ('holder_email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('holder_phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('issued_date', models.DateField(verbose_name='Ausgabedatum')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='Rückgabedatum')),
                ('issued_by', models.CharField(blank=True, max_length=200, verbose_name='Ausgegeben von')),
                ('notes', models.TextField(blank=True, verbose_name='Bemerkungen')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='keys.key', verbose_name='Schlüssel')),
            ],
            options={
                'verbose_name': 'Schlüsselvergabe',
                'verbose_name_plural': 'Schlüsselvergaben',
                'ordering': ['-issued_date', '-created'],
            },
        ),
        migrations.AddField(
            model_name='key',
            name='key_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='keys.keytype', verbose_name='Schlüsseltyp'),
        ),
    ]
